### DISCUSSION TITLE
Advice for configuring rubocop-shopify with Github Actions/Workflows

### DISCUSSION THREAD

**Discussion by jcohenho** [Shopify/ruby-style-guide#335] [Q&A]
I'm trying to add rubocop-shopify to our Github workflows, but the output gives me different errors from my local and appears to be using normal Rubocop instead. For example, I'm getting an error regarding `Layout/SpaceInLambdaLiteral`, but this is not configured in the latest Shopify cop config. Would you be able to share any advice on how best to configure/integrate rubocop-shopify into Github actions/workflows?

Here is my workflow.yml config: 

```
env:
  RUBY_VERSION: 2.7.2

name: Rubocop checks
on: [pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: |
          gem install rubocop-shopify
          gem install rubocop-performance
          gem install rubocop-rails
          gem install rubocop-rspec
      - name: Check code
        run: rubocop
```

**Comment by flavorjones** [comment]
@jcohenho Can you share your `.rubocop.yml` file? I expect you'll need something like this to ensure everything is working:

```yml
require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
inherit_gem:
  rubocop-shopify: rubocop.yml
```

**Reply by jcohenho** [reply]
This is my .rubocop.yml file:

```yml
inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
```
